'$base_config': true

# This skeleton config will be updated from cf-deployment.yml by _stacks.tpl:update

stacks:
  cflinuxfs3:
    # Some dummy settings are included here, even though they will be overridden
    # at install time with values from cf-deployment.yml.  This makes it possible
    # to validate this config file with the values.schema.json validator.
    description: "will be set from cf-deployment"
    install_buildpacks: [will-be-set-from-cf-deployment]

    releases:
      # '$defaults' will be applied from config/releases.yaml
      cflinuxfs3:
        stemcell:
          version: 27.2-7.0.0_374.gb8e8e6af
        version: 0.202.0
      # buildpack versions will be set from cf-deployment
      nginx-buildpack:
        # XXX The manifest lists 1.1.11, kubecf-2.3 used 1.1.5
        version: 1.1.1
      r-buildpack:
        # XXX cf-manifest lists 1.1.7, kubecf-2.3 used 1.1.1
        version: 1.1.0
